name: Linux Test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      shell: bash
      run: |
          mkdir -p circt/build
          cd circt/build
          wget https://github.com/llvm/circt/releases/download/sifive%2F1%2F21%2F0/circt-bin-ubuntu-20.04.tar.gz
          tar -xvf circt-bin-ubuntu-20.04.tar.gz
          cd ../..
          export CIRCT_HOME=$PWD/circt
          apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install pytest
          pip install -e .
    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest tests/
