name: Linux Test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    # based on https://github.com/circt-hls/circt-hls/blob/af089ec837a099cbdcd3c0ae9cd44b651f974fff/.github/workflows/build.yml
    container:
      image: ghcr.io/circt/images/circt-ci-build:20211130162811
    name: Build ${{ matrix.build }} ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build: ["Release"]
        os: [ubuntu-latest]
        compiler:
          - cc: clang
            cxx: clang++

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install pytest
          pip install -e .
    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest tests/
