name: Linux Test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    # based on https://github.com/circt-hls/circt-hls/blob/af089ec837a099cbdcd3c0ae9cd44b651f974fff/.github/workflows/build.yml
    container:
      image: ghcr.io/circt/images/circt-ci-build:20211130162811
    name: Build ${{ matrix.build }} ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build: ["Release"]
        os: [ubuntu-latest]
        compiler:
          - cc: clang
            cxx: clang++

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      shell: bash
      run: |
          wget https://github.com/llvm/circt/releases/download/sifive%2F1%2F21%2F0/circt-bin-ubuntu-20.04.tar.gz
          mkdir -p circuit/build
          tar -xvf circt-bin-ubuntu-20.04.tar.gz
          export CIRCT_HOME=$PATH:$PWD/bin
          apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install pytest
          pip install -e .
    - name: Pytest
      shell: bash -l {0}
      run: |
        export CIRCT_HOME=$PWD/circuit
        pytest tests/
